/**
 * Class for hashing sha1
 *
 * @WolfDroid
 * @version 28/02/2020
 */

//External Library for Hashing
import java.math.BigInteger;                    //Math Library for Converting into BigInteger
import java.security.MessageDigest;             //Security Library for Message Digest Hashing
import java.security.NoSuchAlgorithmException;  //Security Library for Exception Input
  
//Hashing Class
public class sha1Hashing { 
    public static String encryptThisString(String input) { 
        // Looping and testing the input for the Hashing
        try { 
            // Instance of the object from Message Digest 
            MessageDigest MD = MessageDigest.getInstance("SHA-1");
            
            // Calulate the message digest using digest() from input and returning in array bytes.
            byte[] messageDigest = MD.digest(input.getBytes()); 
  
            // Converting array of bytes into Big Integer or Signum Representation
            BigInteger num = new BigInteger(1, messageDigest); 
  
            // Convert message digest into hex value 
            String hashing = num.toString(16); 
            
            // Adding 0s in preceding to make it to 32 bits
            while (hashing.length() < 32) { 
                hashing = "0" + hashing; 
            } 
  
            // returning the value of the output
            return hashing; 
        } 
        // Catching the errors from the message the input
        catch (NoSuchAlgorithmException e) { 
            throw new RuntimeException(e); 
        } 
    } 
  
    // Main class 
    public static void main(String args[]) throws NoSuchAlgorithmException { 
        String s1 = "When there’s a will, there's a way."; 
        System.out.println("HashCode Generated by SHA-1 for : " + encryptThisString(s1)); 
    } 
} 
